### ISSUE TITLE
<Revision> semble être hardcodé pour `folder_path`

### ISSUE THREAD

**Issue by sayanel** [cgwire/gazu#100]
J'ai simplifié ce file tree pour l'exemple:
``` 
PROJECT_FILE_TREE = {
  "preview": {
    "mountpoint": "D:",
    "root": "productions",
    "folder_path": {
        "shot": "<Project>/p<Shot>/<TaskType>/v<Revision>",
    ...
    },
    "file_name": {
        "shot": "<Episode>_s<Sequence>_p<Shot>_<TaskType>_v<Revision>",
        ...
    }
  },
}
``` 
Le pattern `<Revision>` ou `<Version>` fonctionne très bien sur le `file_name` mais lorsqu'il est utilisé pour le `folder_path` il va toujours renvoyer `001` même si la version est supérieure.

**Comment by frankrousseau** [comment]
Hello @sayanel,

You right the parameter is missing. We'll fix that in next release.
https://github.com/cgwire/zou/blob/master/zou/app/blueprints/files/resources.py#L59

Thank you for reporting.

**Comment by sayanel** [comment]
Parfait merci :)

**Comment by frankrousseau** [comment]
Le problème devrait être résolu. Est-ce que ça fonctionne ?

**Comment by sayanel** [comment]
Parfaitement ! Merci
