### ISSUE TITLE
Is there any function to get the web url path to an asset/shot/task?

### ISSUE THREAD

**Issue by Tilix4** [cgwire/gazu#102]
I cannot find any function that would build the web url path to an asset/shot/task.

It would look like:
`gazu.client.get_web_url_path(id)`

and return the url I could copy/paste in the web browser to go directly to the element's page.

**Comment by frankrousseau** [comment]
There is no function for this. However, it would be a good addition.

**Comment by frankrousseau** [comment]
We added function for that:

* https://gazu.cg-wire.com/specs.html#gazu.asset.get_asset_url
* https://gazu.cg-wire.com/specs.html#gazu.shot.get_shot_url
* https://gazu.cg-wire.com/specs.html#gazu.task.get_task_url

**Comment by Tilix4** [comment]
Wonderful! Maybe for a project and an episode? It would work like the Kitsu client and redirect to the appropriate pages.

**Comment by frankrousseau** [comment]
For the project it's already there: https://gazu.cg-wire.com/specs.html#gazu.project.get_project_url

It's still missing for the episode.

**Comment by frankrousseau** [comment]
The episode function was added in the last release. Is it good for you?
