### ISSUE TITLE
Simplify gazu.task.set_main_preview arguments

### ISSUE THREAD

**Issue by aboellinger** [cgwire/gazu#107]
### Problem

The `gazu.task.set_main_preview` methods takes two arguments `asset` and `preview_file`
As discussed on slack this 
- is unnecessarily verbose as the `asset` can actually be inferred from `preview_file->task->entity`.
- might cause weird situations such as using a preview on an unrelated asset.

### Proposed solution

We could refactor `gazu.task.set_main_preview`  to take only `preview_file` as an argument.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
