### ISSUE TITLE
Flag `relations` does not work for gazu.task.all_tasks_for_shot(shot)

### ISSUE THREAD

**Issue by sayanel** [cgwire/gazu#113]
The route `/api/data/shots/{shot_id}/tasks?relations=True` does not take into consideration the flag`relations=true` and does not retrieve the `assignees` list

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by sayanel** [comment]
Yes I can try again but next week sorry ..

**Comment by sayanel** [comment]
It's all good !

**Comment by frankrousseau** [comment]
Great! For your information, `client.fetch_all("shots/%s/tasks?relations=true"` was expected (note the lowercase for true).
