### ISSUE TITLE
all tasks for person vs done tasks

### ISSUE THREAD

**Issue by OxB03** [cgwire/gazu#119]
Hi ... 

Not sure if this is correct, but the request seems the same for both all_tasks_for_person and all_done_tasks_for_person ... 

task.py, line 206 - 223

`@cache
def all_tasks_for_person(person):
    """
    Returns:
        list: Tasks that are not done for given person (only for open projects).
    """
    person = normalize_model_parameter(person)
    return client.fetch_all("persons/%s/tasks" % person["id"])

@cache
def all_done_tasks_for_person(person):
    """
    Returns:
        list: Tasks that are done for given person (only for open projects).
    """
    person = normalize_model_parameter(person)
    return client.fetch_all("persons/%s/tasks" % person["id"])
`

I think the all_done_tasks_for_person needs to call something else ?

**Comment by frankrousseau** [comment]
Yes, you're right. It seems that there is something wrong. I will look at it.
