### ISSUE TITLE
More context when requesting a shot or an asset ?

### ISSUE THREAD

**Issue by flablog** [cgwire/gazu#12]
When getting a specific shot information using : 
```get_shot({'id':'98685e03-e787-4fa5-9be1-840a2cc88cff'})```

We get useful information such as : 
```{u'canceled': False,
u'created_at': u'2017-11-23T14:45:02.569117',
u'data': {},
u'description': None,
u'entities_in': [],
u'entities_out': [u'28fd5ee2-8d4f-439d-804f-4c0110d3248e',
                  u'8093f0e7-cb45-464c-a709-a88e3a10f04b'],
u'entity_type_id': u'41f39774-d77d-4428-8124-625cd2acb86f',
u'id': u'98685e03-e787-4fa5-9be1-840a2cc88cff',
u'name': u'P004',
u'parent_id': u'13280382-cfe4-4c12-a367-e831fa760e18',
u'preview_file_id': u'479633bf-0905-4905-9906-77596cd03694',
u'project_id': u'7896a9aa-dd4b-4abb-93a5-d96bd9828c7f',
u'shotgun_id': None,
u'type': u'Entity',
u'updated_at': u'2017-11-23T16:59:20.191010'}
```

But the name (P004) is not enough to contextualize the shot for the user. What is its sequence, episode or projet ? What if I've 10 episodes, with 10 sequences and all of them have a shot P0004 ?

To get the full context, I need to do 3 more requests : 
* one for the projet name (the id is provided)
* one for the sequence name (probably parent_id ?)
* one for the episode name (probably the parent_id/parent_id ?)

should that information be provided as default information ? Or at least as ids (episode_id and sequence_id) ? As shots are always (?) defined by their parent : sequence/episode/project. And I'm thinking of the same for assets.

Does it add too much internal load during basic requests ?

**Comment by frankrousseau** [comment]
Thank you @flablog for this suggestion. The behind idea of Gazu is to make life of TDs as simple as possible. Your feature request totally matches this goal. Requesting shots and assets is very common, so I add this to my short-term roadmap. 

Beside shots, there are several entities concerned by this feature:

* Asset (as mentioned in your issue)
* Sequence
* Scene

I don't think it adds too much technical overhead. As long as it occurs only for single instance resource. If I need to add it for every shot list, it is more complex. So let's add it to single instance resource first. We'll see later if it's needed in other circumstances.

**Comment by frankrousseau** [comment]
This issue was solved in the last version of Zou. Could you confirm it works as expected?

**Comment by frankrousseau** [comment]
ping @flablog
