### ISSUE TITLE
Error while starting with gazu python

### ISSUE THREAD

**Issue by artofka** [cgwire/gazu#135]
Error while starting with gazu python:
```
import gazu
gazu.client.set_host("localhost/api")
gazu.log_in("********@gmail.com", "*********")
```

> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/artem/.local/lib/python2.7/site-packages/gazu/__init__.py", line 34, in log_in
>     "auth/login", {"email": email, "password": password}
>   File "/home/artem/.local/lib/python2.7/site-packages/gazu/client.py", line 161, in post
>     get_full_url(path), json=data, headers=make_auth_header()
>   File "/home/artem/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/home/artem/.local/lib/python2.7/site-packages/requests/sessions.py", line 519, in request
>     prep = self.prepare_request(req)
>   File "/home/artem/.local/lib/python2.7/site-packages/requests/sessions.py", line 462, in prepare_request
>     hooks=merge_hooks(request.hooks, self.hooks),
>   File "/home/artem/.local/lib/python2.7/site-packages/requests/models.py", line 313, in prepare
>     self.prepare_url(url, params)
>   File "/home/artem/.local/lib/python2.7/site-packages/requests/models.py", line 387, in prepare_url
>     raise MissingSchema(error)
> requests.exceptions.MissingSchema: Invalid URL 'localhost/api/auth/login': No schema supplied. Perhaps you meant http://localhost/api/auth/login?

Python 2, Ubuntu 18.02, 
`{"api": "Zou", "version": "0.11.48"}`

**Comment by aboellinger** [comment]
I'm assuming that you get this `{"api": "Zou", "version": "0.11.48"}` as  a response in your browser, wich indicates that the url is working properly and discards issues related to, for instance, a missing `localhost` port.

Can you try to add the `http://` protocol at the beginning of the host url ?
```py
import gazu
gazu.client.set_host("http://localhost/api")  # <-- Here
gazu.log_in("********@gmail.com", "*********")
```

I think that is what is suggested at the end of the error message:
> `Perhaps you meant http://localhost/api/auth/login?`

**Comment by artofka** [comment]
> I'm assuming that you get this `{"api": "Zou", "version": "0.11.48"}` as a response in your browser, wich indicates that the url is working properly and discards issues related to, for instance, a missing `localhost` port.
> 
> Can you try to add the `http://` protocol at the beginning of the host url ?
> 
> ```python
> import gazu
> gazu.client.set_host("http://localhost/api")  # <-- Here
> gazu.log_in("********@gmail.com", "*********")
> ```
> 
> I think that is what is suggested at the end of the error message:
> 
> > `Perhaps you meant http://localhost/api/auth/login?`

Now that's works! Thanks!
