### ISSUE TITLE
package installation from setup.py

### ISSUE THREAD

**Issue by firegreen** [cgwire/gazu#158]
When I install the package via setup.py, the client.py importation failed because of `default_client` referencing

adding `default_client = None` when "running in setup mode" should be enough to fix this issue

**Comment by frankrousseau** [comment]
Thank you for reporting this. I'm going to have a look at it.

**Comment by frankrousseau** [comment]
I published a new version. Can you try it?

**Comment by firegreen** [comment]
perfect, thanks !
