### ISSUE TITLE
Asset name is capitalized when created

### ISSUE THREAD

**Issue by flablog** [cgwire/gazu#16]
When creating an asset, its name is capitalized no matter how it was provided.
```
a = gazu.asset.new_asset(project={'id':project_id}, asset_type={'id':lib_types[t]}, name="MyAwesomeNameXXX", description="")
```
will be created as "Myawesomenamexxx"

I ve to then do something like : 

```
name = "MyAwesomeNameXXX"
# Add my asset
a = gazu.asset.new_asset(project={'id':project_id}, asset_type={'id':lib_types[t]}, name=name, description="")
# Update the name of the created asset...
gazu.client.put("data/entities/%s"% a['id'], {'name':name})
```
The last line is because I've found yet the gazu.asset.update() command or something. I'll add it later.

**Comment by flablog** [comment]
My bad....
An input was wrong in the code

**Comment by frankrousseau** [comment]
I removed the forced capitalization in PR zou#49
