### ISSUE TITLE
get_task_status() on tasks created using new_shot() gives error

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/gazu#162]
I have written a comments-function that checks the task_dict for its status to make sure it uses the same status as before.
When I run this on new shots that I have created using gazu.shot.new_shot() I'm getting the error that it can't find task["task_status_id"] inside function get_task_status() in task.py.

It seems like newly created tasks don't have the task_status_id key, thus throwing this error. The key should exist but be empty so if no task status is applied the return would be empty instead of an error.

**Comment by EmberLightVFX** [comment]
Sorry, I accedentally passed a task_type_dict instead of the task_dict.

**Comment by ddesmond** [comment]
this was messing with me too! :)

**Comment by frankrousseau** [comment]
This function was changed, now the task_status_id is expected, like for other functions.
