### ISSUE TITLE
get_shot_url() and get_asset_url() returns 'project_id' when passing IDs

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/gazu#163]
get_shot_url() and get_asset_url() returns the string 'project_id' when passing IDs even tho the docs says it should be able to read IDs

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll have a look to this problem when we find time to work on it.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
