### ISSUE TITLE
get_shot_url() and get_asset_url() don't add the episode part to the url

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/gazu#164]
get_shot_url() and get_asset_url() don't add the episode part to the url when working in a TV-Show project.
I'm getting the url:
.../productions/beebe2de-6fb2-43e0-86d4-6c5e519b1866/shots/178e1ab3-16e4-4610-b8f4-027205e3e1b4/
when I should get the url:
.../productions/beebe2de-6fb2-43e0-86d4-6c5e519b1866/episodes/5b5b7a45-a596-4231-aef8-9f25842c9c87/shots/178e1ab3-16e4-4610-b8f4-027205e3e1b4

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll have a look to this problem when we find time to work on it.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by EmberLightVFX** [comment]
Yep, it's now working flawlessly!
