### ISSUE TITLE
Error when trying to get a preview for a task

### ISSUE THREAD

**Issue by ddesmond** [cgwire/gazu#168]
getting errors (tested from 0.8.0 to 0.8.6) from kitsu docker (seems latest, got fresh pull half hour ago 22oct 9am)

```
all_tasks = gazu.user.all_tasks_to_do()
for task in all_tasks:
    print task["entity_name"]," - ", task["task_type_name"]
    prevs = gazu.files.get_all_preview_files_for_task(task)
    print len(prevs)
    print prevs
    for preview in prevs:
        print preview
        path = "thumbs/target.png"
        gazu.files.download_preview_file_thumbnail(preview, path)

```
this piece of code yields error below

```
Traceback (most recent call last):
    gazu.files.download_preview_file_thumbnail(preview, path)
  File "/Users/des/Library/Python/2.7/lib/python/site-packages/gazu/files.py", line 1115, in download_preview_file_thumbnail
    client=client
  File "/Users/des/Library/Python/2.7/lib/python/site-packages/gazu/client.py", line 404, in download
    stream=True
AttributeError: __exit__
```

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll have a look to this problem when we find time to work on it.

**Comment by ddesmond** [comment]
The root cause was in older requests library which was being force by Conductor.app (rendering service). Ive wrote them to update their libs and removed their app from my pythonpath. 
Thanks @BigRoy for debuging session today. Learned a ton. Will close this issue since its not gazu related. Altough it would be nice to write a nicer error message :)
