### ISSUE TITLE
Method to restore a shot

### ISSUE THREAD

**Issue by NeirdaP** [cgwire/gazu#178]
Hi,

I saw in the web interface that we could restore a deleted shot but I can't manage to find a method in gazu to do the same thing. 

Is it an oversight ? Or am i missing something here ?

Thank you

**Comment by frankrousseau** [comment]
There is no helper for that. What you can do is to update shot data by setting the `canceled` field to `False`.

**Comment by NeirdaP** [comment]
Alright, I'll do that :)

Thank you for your help !

**Comment by frankrousseau** [comment]
Great!

**Comment by frankrousseau** [comment]
I added the restore function. It will be included in the next release.
