### ISSUE TITLE
Data is not saved when creating an entity

### ISSUE THREAD

**Issue by flablog** [cgwire/gazu#18]
When creating a shot for example, my dict data is not save in the database

```
data={'frame_in':1, 'frame_out':25}
shot = gazu.client.post("/data/projects/%s/shots"% project['id'], {'name':"shotName", 'sequence_id':sequence['id'], 'data':data})
```

the current workaround is, just after doing the gazu.client.post, making a new update query with the newly created shot : 

```
data={'frame_in':1, 'frame_out':25}
shot = gazu.client.post("/data/projects/%s/shots"% project['id'], {'name':"shotName", 'sequence_id':sequence['id'], 'data':data})
gazu.client.put("data/entities/%s"% shot['id'], {'data':data})
```

**Comment by flablog** [comment]
Yes, and there is no function to create/update a shot in gazu currently :)

**Comment by g-LuL** [comment]
I can confirm this issue. Same result when I try to create a shot.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
