### ISSUE TITLE
Fonction de tri par projet manquante

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#180]
Il y a des fonctions existantes qui permettent de filtrer les données par projet, mais il y en a une particulière qui manque.

Celle-ci existe: `gazu.asset.all_asset_types_for_project(project, client=<gazu.client.KitsuClient object>)`
Celle-ci serait pratique: `gazu.task.all_task_types_for_project(project, client=<gazu.client.KitsuClient object>)`

Il est possible de récupérer les IDs de ceux-ci directement dans l'objet du projet, mais ce n'est pas pratique.
De plus, la fonction `gazu.task.get_task_type` n'est pas présente dans la documentation.

**Comment by frankrousseau** [comment]
Merci pour le rapport. On va regarder ça.

**Comment by frankrousseau** [comment]
La fonction que tu demandais a été ajoutée. Est-ce que c'est bon pour toi désormais ?
