### ISSUE TITLE
Attachment_files after creating a comment

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#186]
In the same way that you can add preview files after sending a comment, it would be practical for certain cases to allow the addition afterwards.

Une méthode `gazu.task.add_attachment` peut-être ?

**Comment by frankrousseau** [comment]
Thank you @Arubinu for the suggestion.

**Comment by EvanBldy** [comment]
Hello @Arubinu,
It's done in this PR https://github.com/cgwire/gazu/pull/227
Thanks for the report
