### ISSUE TITLE
Comment by ID

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#187]
It is currently impossible to retrieve a comment with its ID.
The `gazu.entity.get_entity` method does not allow you to do this either.

Would it be possible to add this possibility to `gazu.entity.get_entity`?
Secondly, maybe a `gazu.task.get_comment` method?

**Comment by frankrousseau** [comment]
Thank you @Arubinu for the suggestion. A `get_comment` section is the right solution. Entities are production assets, shots, sequences and episodes.

**Comment by EvanBldy** [comment]
Hello @Arubinu,
It's done in this PR https://github.com/cgwire/gazu/pull/227
Thanks for the report
