### ISSUE TITLE
get_all_preview_files_for_task for assets

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#188]
From my testing, `gazu.files.get_all_preview_files_for_task` does not work for assets.

If we could have `gazu.files.get_all_attachment_files_for_task`, that could be interesting too.

**Comment by frankrousseau** [comment]
Thank you @Arubinu for the suggestions.

**Comment by EvanBldy** [comment]
Hello @Arubinu 
This is added in this PR https://github.com/cgwire/gazu/pull/226
Thanks for the report
