### ISSUE TITLE
Missing methods for assets

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#189]
I will see these useful methods so as not to have to ask questions about the contents of the object:
 - `get_episode_for_asset` would fetch the episode linked to an asset, if there is one.
 - `get_asset_type_for_asset` would also be handy, since it is needed when creating an asset.

**Comment by frankrousseau** [comment]
Thank you for all the suggestions!

**Comment by EvanBldy** [comment]
Hi @Arubinu,
I have done what you need in this PR : https://github.com/cgwire/gazu/pull/249
