### ISSUE TITLE
Broken import 

### ISSUE THREAD

**Issue by aboellinger** [cgwire/gazu#198]
# Problem 

`gazu` import broken due to #197

On a clean environment, after installing gazu with pip we get 

```
(venv) C:\Users\aboellinger>python -c "import gazu"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\aboellinger\venv\lib\site-packages\gazu\__init__.py", line 4, in <module>
    from . import events
  File "C:\Users\aboellinger\venv\lib\site-packages\gazu\events.py", line 4, in <module>
    import socketio
ModuleNotFoundError: No module named 'socketio'
```

**Comment by aboellinger** [comment]
I am fixing it locally, will submit a PR

**Comment by EvanBldy** [comment]
Hello @aboellinger,
Sorry it's because I forgot to upgrade requirements in setup.cfg

**Comment by aboellinger** [comment]
Yes I am taking a look at it, but haven't figured out how to translate the "conditions" on python version to setup.cfg.

I am also changing `requirements.txt` to [the pattern found in the zou repository](https://github.com/cgwire/zou/blob/e02485e1c44b6f8701e523b978b952ed9033d633/requirements.txt), to have a unique source of truth regarding dependencies (`setup.cfg`)

**Comment by EvanBldy** [comment]
The conditions are the same in setup.cfg. Take a look at : https://github.com/cgwire/zou/blob/e02485e1c44b6f8701e523b978b952ed9033d633/setup.cfg

Yeah I think it's a good idea!

**Comment by aboellinger** [comment]
Thanks, I got that sorted out, but now I am getting a problem when pip runs `setup.cfg` : 

since `setup.cfg` imports `gazu` (to get the `__version__`), we end up trying to import `socketio` (from `gazu.__init__`) *before* we install it... 🙃 

```
(venv) C:\Users\aboellinger>pip install C:/dev/github/gazu
Processing c:\dev\github\gazu
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ABOELL~1\AppData\Local\Temp\pip-req-build-gnxcj7g8\setup.py", line 4, in <module>
        from gazu.__version__ import __version__
      File "C:\Users\ABOELL~1\AppData\Local\Temp\pip-req-build-gnxcj7g8\gazu\__init__.py", line 4, in <module>
        from . import events
      File "C:\Users\ABOELL~1\AppData\Local\Temp\pip-req-build-gnxcj7g8\gazu\events.py", line 4, in <module>
        import socketio
    ModuleNotFoundError: No module named 'socketio'
```

**Comment by EvanBldy** [comment]
Can you move the import socketio directly in the function init (in gazu/events.py) ? 
It will be good after that.
Thanks @aboellinger

**Comment by aboellinger** [comment]
Yes, that is an option I will keep in mind. I went for another (reading the version without running imports), as I think we might run into this issue with other dependencies in the future.

Now things work on python 3.7 but I still have issues testing with python 2.7, but I'll create the PR so we can continue the discussion on it.

**Comment by aboellinger** [comment]
By the way @EvanBldy did you test for python 2.7 ? 

Even through your `requirements.txt` I get this error, that seems to indicate that `python-socketio[client]==5.2.1` is not compatible with python 2.7 :
```
ERROR: Could not find a version that satisfies the requirement bidict>=0.21.0 (from python-socketio[client]==5.2.1; python_version == "2.7"->gazu==0.8.20) (from versions: 0.1.5, 0.2.1, 0.3.0, 0.3.1, 0.9.0rc0, 0.9.0.post1, 0.10.0, 0.10.0.post1, 0.11.0, 0.12.0.post1, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.15.0.dev0, 0.15.0.dev1, 0.15.0rc1, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4)
ERROR: No matching distribution found for bidict>=0.21.0 (from python-socketio[client]==5.2.1; python_version == "2.7"->gazu==0.8.20)
```

**Comment by aboellinger** [comment]
Just saw you questions on the PR #199, moving the discussion there ;)

**Comment by EvanBldy** [comment]
Thank you!
