### ISSUE TITLE
What is name="main" in a task query ?

### ISSUE THREAD

**Issue by flablog** [cgwire/gazu#20]
If I query a precise task like

`task = gazu.client.get("data/tasks/323f103e-e440-453c-9d94-370ef534f973")`

I've a `name` key, but it's value is "main" no matter if it's a shot or an asset task.
Why is it not the name of the task ? Like "Layout" or "Modeling" ?

We've to now query the task_types using the `task_type_id` key of the task object to know which task we are talking about.
Maybe as issue #12 (context for shots and assets) , tasks can have some more quick context, like

```
task['name']   #   Anim-Main, Anim-Crowd, ...
task['department'] # Animation
task['department_id']  
task['status']   #   WFA, ... # Not only status_id ?
```

**Comment by frankrousseau** [comment]
Hey @flablog!

* The name refers to a specific action you would like to track outside of the main task. It's similar to task name in Shotgun. But it doesn't appear in Kitsu. So I think you can ignore it.
*  What you are looking for is gazu.client.get("data/tasks/323f103e-e440-453c-9d94-370ef534f973/full"). It should return much more information about the task.
