### ISSUE TITLE
fetch all tasks for assets in an episode in one query

### ISSUE THREAD

**Issue by mchaptel** [cgwire/gazu#203]
Would it be possible to have the equivalent of `gazu.task.all_shot_tasks_for_episode()` but for the assets linked to the episode?

The current solution poses a problem as it requires a query for the list of assets then one query per asset, which adds up.

Something like `gazu.task.all_asset_tasks_for_episode()` would be great! Is there an existing route we can use in the meantime?

**Comment by EvanBldy** [comment]
Hello @mchaptel 
This is added in this PR https://github.com/cgwire/gazu/pull/227
Thanks for the report
