### ISSUE TITLE
gazu.files.get_all_preview_files_for_task(task) gives all the Kitsu instance previews 

### ISSUE THREAD

**Issue by VictorChapal** [cgwire/gazu#206]
Hi !
From my testing, `gazu.files.get_all_preview_files_for_task(task)` gives all the Kitsu instance previews instead of giving the previews linked to the task we give in parameter.

**Comment by EvanBldy** [comment]
Hello @VictorChapal,
The problem is in Zou API not in Gazu so we will fix this in Zou.
Thanks for the suggestion and your time :)
I will keep you in touch here
