### ISSUE TITLE
Get all_open_projects for admin user

### ISSUE THREAD

**Issue by johhnry** [cgwire/gazu#214]
Hi,

I am using Zou `v0.13.13` and gazu `v0.8.23`.

Seeing the [source code](https://github.com/cgwire/gazu/blob/master/gazu/user.py#L14) for the `gazu.user.all_open_projects`, it says this:

```python
def all_open_projects(client=default):
    """
    Returns:
        list: Projects for which the user is part of the team. Admins see all
        projects
    """
```

Which means that the Admin user can get all the projects. This is true in the Kitsu interface but it's using `/api/data/user/context` (which returns all the projects, asset and task types...).

However doing this with gazu returns an empty list:

```python
import gazu

gazu.client.set_host("http://zou-url.fr/api")
gazu.log_in("admin@example.com", "mysecretpassword")

projects = gazu.user.all_open_projects()
print(projects)
```

```
[]
```

It would be nice to have the same behavior as user/context but with the projects so the admin can get all the running projects, not just the ones that he's working on.

**Comment by EvanBldy** [comment]
Hi @johhnry,
I have made the fix here : https://github.com/cgwire/zou/pull/617
Can you try and close if it's okay for you ?

**Comment by johhnry** [comment]
Hi @EvanBldy,

Thanks for the fix, I'll try to test it if I have time. Otherwise you can close it if needed

**Comment by EvanBldy** [comment]
@johhnry,
I close it will be okay :)
