### ISSUE TITLE
Get list of shots related to a task

### ISSUE THREAD

**Issue by Pullusb** [cgwire/gazu#223]
In Web UI Shot page, when we click on the header of a task we get a list of all shots relative to this task.
We don't have a command to get that with API.
We need Something like `gazu.task.all_tasks_for_task_type()` but only for a single episode

**Comment by frankrousseau** [comment]
Thank you for the report!

**Comment by frankrousseau** [comment]
You have now two new functions:

* `all_tasks_for_task_type` can now be filtered by `episode`.
* `all_tasks_for_project` and filter with `episode` and ` task_type`

**Comment by Pullusb** [comment]
Nice ! Thank you
