### ISSUE TITLE
Creating a shot raise an error

### ISSUE THREAD

**Issue by g-LuL** [cgwire/gazu#23]
When i create a shot with 
`gazu.shot.new_shot(project,sequence,name)`
the shot is created without any trouble.
But when i try this :
`gazu.shot.new_shot(project,sequence,name,frame_in=10,frame_out=100)`
Gazu raise : `ValueError: Circular reference detected`

**Comment by frankrousseau** [comment]
It should be fixed can you try again with the latest version (0.4.0 for zou and gazu)

**Comment by g-LuL** [comment]
Problem solved ! Thanks @frankrousseau
