### ISSUE TITLE
'delete:<entity>' should pass the whole deleted entity like a 'get_<entity>' would do

### ISSUE THREAD

**Issue by Tilix4** [cgwire/gazu#239]
To keep another DB up-to-date with zou we need to react to events. `delete:` events pass as `data` only the id of the deleted entity and of the project. It's tough to match another DB which doesn't represent the entities the same way zou does.

To make it easier, it'd be very helpful `delete:<entity>` emits the whole deleted entity into `data` like `get_<entity>()` would do.

**Comment by EvanBldy** [comment]
Hello @Tilix4,
Thanks for the suggestion!
For now I only added the entity_id of a task to the task:delete event (in this PR https://github.com/cgwire/zou/pull/427). If you need more information in a specific event tell me what you need. :)
Have a nice day!

**Comment by Tilix4** [comment]
> If you need more information in a specific event tell me what you need.
Hi thanks! It'd be great to also have the `task_type_id` :)

**Comment by EvanBldy** [comment]
It's added in the PR :)

**Comment by Tilix4** [comment]
Great thanks!
