### ISSUE TITLE
gazu.entity.get_entity_by_name returns wrong result

### ISSUE THREAD

**Issue by Maxiriton** [cgwire/gazu#252]
Hello,

I have to retrieve a task based on a string and to do so I parse my string which is composed like that :  "sequenceName_shotName_TaskTypename_XXX'

With these three elements and using Gazu, I could retrieve the zou task object that I want. To retrieve the sequence object, I use gazu.entity.entiy_by_name(sequenceName).

However, in the specific case where you have two projects open and both have a sequence with the same name (which is quite likely to happen for a sequence named sq0001 for example), it seems that it is impossible to limit the entity search for a specific project and zou returns the first that matches, in my case the wrong result. 

I've found a workaround by iterating over all the sequences in a given projects and return the one that matches but maybe it would be interesting to have an optional parameter for this API function to limit the scope of the research. 

Thanks,
Henri

**Comment by EvanBldy** [comment]
Hi @Maxiriton,
Thanks for the report :)
As @frankrousseau said you should use gazu.shot.get_sequence_by_name instead. :)
But I have added a new argument to gazu.entity.get_entity_by_name "project" which can filter them by project. It's in this PR : https://github.com/cgwire/gazu/pull/262
Can you close the issue if it's okay for you ?

Have a nice day :)

**Comment by Maxiriton** [comment]
Hello Evan,

Thanks for your answer. I somehow missed that Frank answered as well, sorry about that. Adding the project filter seems perfect, thanks a lot. :)
