### ISSUE TITLE
Function get_ task_ URL Args description error

### ISSUE THREAD

**Issue by fyplclfkr** [cgwire/gazu#253]
https://github.com/cgwire/gazu/blob/517009ac955022e518b1339370c050cb61317f65/gazu/task.py#L1018
Args must be dict and have the task.id and task.project_id,not str

**Comment by frankrousseau** [comment]
Thanks @fyplclfkr for reporting!

**Comment by EvanBldy** [comment]
Hi @fyplclfkr,
Thanks for the report
It should be fixed in this PR : https://github.com/cgwire/gazu/pull/262
Can you try and close if it's okay for you ? 
Thanks, have a nice day :)
