### ISSUE TITLE
host_is_valid does not work when using LDAP

### ISSUE THREAD

**Issue by ninglesby** [cgwire/gazu#254]
https://github.com/cgwire/gazu/blob/507fa8c246b0f446523f88ca962667f60a5ffa5d/gazu/client.py#L68

If using LDAP `gazu.client.host_is_valid()` does not work as expected.  It returns False with a valid server and prints out an error message.

```
A server error occured!

Server stacktrace:
No stacktrace sent by the server
Error message:
password is mandatory in simple bind
```

Looks like the problem is the function is attempting to login with an empty string for the username and password which is causing a server error. I tested a workaround if the function uses white a single white space as opposed to an empty string it will work. Is it worth doing the fix in gazu or is this something that should be addressed in zou?

original
```
post("auth/login", {"email": "", "password": ""})
```
workaround
```
post("auth/login", {"email": " ", "password": " "})
```

**Comment by frankrousseau** [comment]
Thanks @ninglesby for reporting!

**Comment by EvanBldy** [comment]
Hi @ninglesby, 
Thanks for the report :)
With this PR from Zou : https://github.com/cgwire/zou/pull/533
And this PR from Gazu : https://github.com/cgwire/gazu/pull/262
If it's good for you, can you close the issue ?
Have a nice day

**Comment by ninglesby** [comment]
Thanks @EvanBldy !
