### ISSUE TITLE
gazu.asset.all_asset_types_for_project does not accept id.

### ISSUE THREAD

**Issue by jhoolmans** [cgwire/gazu#259]
Docs say that it accepts a str/dict. But it does not get normalized like in the other functions.

https://github.com/cgwire/gazu/blob/95dc42fa58535f82f159d62e5517fc25239f1362/gazu/asset.py#L265-L274

**Comment by EvanBldy** [comment]
Hi @jhoolmans,
Thanks for reporting that and for the PR :)
