### ISSUE TITLE
gazu.asset.get_asset_by_name() return shot item.

### ISSUE THREAD

**Issue by col-one** [cgwire/gazu#26]
gazu.asset.get_asset_by_name() return shot item.

**Comment by flablog** [comment]
Yes, there is an issue with the current way of making a request with a name, as you can not specify the entity_type.
You will have the very same problem with the function you've committed today, `get_episode_by_name()`, which can be used to search for any entity. Could be an asset, a sequence, someone or a shot too.

**Comment by col-one** [comment]
You are absolutely right, type of any items is always "entity", Fix that, It probably requires more deep modifications ?
