### ISSUE TITLE
Metadata names : `-` and `_` are swapped

### ISSUE THREAD

**Issue by dragonbleapiece** [cgwire/gazu#263]
The characters `-` and `_` are swapped between the interface and the server for metadata names.

![image](https://user-images.githubusercontent.com/27817484/198565916-747888e9-e4b2-4f38-87a1-684f349ac5cc.png)
![image](https://user-images.githubusercontent.com/27817484/198565936-c485e1ec-ff89-4664-b6cf-91ea2d9c0d94.png)

**Comment by EvanBldy** [comment]
Hi @dragonbleapiece,
Thanks for the report but it's not a bug the metadata descriptors names are slugified. So this is the same slug for both. But why do you need two metadata descriptors with the same name ?

**Comment by dragonbleapiece** [comment]
Ok, I will make it clearer.
May you give me the slugified version for the next outputs, please ?

| Input | Slugified |
|---|---|
| hello world | ? |
| hello-world | ? |
| hello_world | ? |

I'm trying to understand what are the rules of the slugify you use.

**Comment by EvanBldy** [comment]
I will add a unicity constraint to block that :)

We use the [python-slugify](https://pypi.org/project/python-slugify/) library. We only do `slugify.slugify(name)`

Input | Slugified
-- | --
hello world | hello-world
hello-world | hello-world
hello_world | hello-world

**Comment by dragonbleapiece** [comment]
Thank you !
To finish my explanation : in the example I gave, we get in the current data

| Input | Expected | Currently |
|---|---|---|
| hello world | hello-world | hello-world |
| hello-world | hello-world | hello_world |
| hello_world | hello-world | hello-world |

The metadata descriptors with the same names were created because I didn't get what I expected and are there to illustrate this strange behavior.

**Comment by EvanBldy** [comment]
Ah yeah I see... There's a problem in the code. 
At this [line](https://github.com/cgwire/zou/blob/823328030835dc40d80bc4588df50f34b7ce297a/zou/app/services/projects_service.py#L402) when we create the metadata discriptor it uses slugify with the default separator ("-") and at this other when we update a metadata descriptor [line](https://github.com/cgwire/zou/blob/823328030835dc40d80bc4588df50f34b7ce297a/zou/app/services/projects_service.py#L454) it uses the separator given as argument ("_"). I will change that to use always "-".

**Comment by EvanBldy** [comment]
I have changed the slugify of field_name to always use "_" and added a unique constraint for field_name, project_id, entity_type. 
It's in this PR : https://github.com/cgwire/zou/pull/539
With that it will be impossible to create two metadata descriptors with same field_name for same project and entity type.
