### ISSUE TITLE
gazu.person.get_person_by_full_name edge cases

### ISSUE THREAD

**Issue by frankrousseau** [cgwire/gazu#267]
From our Discord:

"
Hi @CGWire Team, a tiny issue with the gazu function gazu.person.get_person_by_full_name,
we have a person with 2 spaces " " in his name, so the  line 88 first_name, last_name = full_name.lower().split(" ") does not work
maybe split(" ", 1) should fix that but it does not manage first name with spaces, you may plan another function that takes separately the first and the last names
"

**Comment by EvanBldy** [comment]
Hi @frankrousseau,
It should be fixed with the last release of Gazu (0.10.0) since we can query directly the full name with a query string in Zou (/api/data/persons?full_name=xxx). I let you close this issue if it's okay for you.
