### ISSUE TITLE
Metadata "field_name" changes with "name"

### ISSUE THREAD

**Issue by Trukasss** [cgwire/gazu#268]
Irrégularités de la valeur "field_name" des métadatas.
Cette clé est pratique pour se référencer à une métadata, cependant elle change si un utilisateur modifie le nom d'affichage.
Vu que cette valeur n'est accessible que via scripting, j'ai l'impression qu'idéalement elle ne devrait pas pouvoir être changée par les utilisateurs et utilisatrices. 

```py
import gazu

gazu.client.set_host("")
gazu.log_in("", "")
p = gazu.project.get_project_by_name("")
ma_metadata = gazu.project.get_metadata_descriptor(p, "b63555d6-5887-47f2-bd17-e0595a8ba9e8")

print(f"name : {ma_metadata['name']}, field_name : {ma_metadata['field_name']}") 
# >>> name : NOM_TST, field_name : nom_tst

# utilisateur change le nom de la metadata 'NOM_TST' à 'NOM_TST2'

print(f"name : {ma_metadata['name']}, field_name : {ma_metadata['field_name']}") 
# >>> name : NOM_TST2, field_name : nom_tst2

# Donc le 'field_name' change si le nom d'affichage est modifié par un utilisateur.
# Difficile de tracker la metadata via code à moins de manipuler directement l'ID.
```

**Comment by frankrousseau** [comment]
It's a tough question. We made this to ensure the metadata dict is human readable. The user may need to correct a name.

**Comment by frankrousseau** [comment]
We prefer not to change this behavior for the moment. We already have a lot of work and there are pros and cons to both approaches.
