### ISSUE TITLE
gazu.task.all_tasks_for_project() and gazu.entity.get_entity_by_name() can be used only as Studio Manager

### ISSUE THREAD

**Issue by BaptisteDelos** [cgwire/gazu#269]
## Issue
The following functions raise a `gazu.exception.NotAllowedException` exception when the role of the logged user is not *Studio Manager*:
- `gazu.task.all_tasks_for_project()`
- `gazu.entity.get_entity_by_name()`

#### `gazu.task.all_tasks_for_project()`

- Explicitly request shot and assets tasks with `gazu.shot.all_shots_for_project()` and `gazu.asset.all_assets_for_project()` in combination with `gazu.task.all_tasks_for_shot()` and `gazu.task.all_tasks_for_asset()`.
- Request tasks of all types existing in the project with `gazu.task.all_task_types_for_project()` in combination with `gazu.task.all_tasks_for_task_type()`.

#### `gazu.entity.get_entity_by_name()`

Use `gazu.shot.get_shot_by_name()` and `gazu.asset.get_asset_by_name()`.

**Comment by frankrousseau** [comment]
Thank you for reporting. It should be fixed. If it's not the case, feel free to reopen the issue.
