### ISSUE TITLE
Add gazu.casting.get_[entitie]_casting() and gazu.casting.update_[entitie]_casting() methods for all entities

### ISSUE THREAD

**Issue by angel-k** [cgwire/gazu#271]
Just like the existing methods for `assets` and `shots`, some of the corresponding methods for `episodes` and upcoming `sequences` are missing:
- `gazu.casting.get_episode_casting(episode)`
- `gazu.casting.update_episode_casting(project, episode, casting)`
- `gazu.casting.update_sequence_casting(project, sequence, casting)`

I think it would be useful to add them.
Thank you

**Comment by frankrousseau** [comment]
These functions will be added in the next release for the episode.

The sequence casting doesn't exist in the Kitsu UI.

**Comment by frankrousseau** [comment]
The functions were added.
