### ISSUE TITLE
Update gazu.log_in() to handle OTP

### ISSUE THREAD

**Issue by angel-k** [cgwire/gazu#272]
Now that OTP has been added to Kitsu, the method should support it

Thank you

**Comment by EvanBldy** [comment]
Hi @angel-k !
Thanks I will add that soon :)

**Comment by EvanBldy** [comment]
Hi @angel-k, it's added in the last version :)
Can you close the issue if it's okay for you ?

**Comment by angel-k** [comment]
Hi ! I tested it with TOTP, it works.
It would be nice to update the documentation with examples of use and integration for TOTP and FIDO keys 😉
Thanks
