### ISSUE TITLE
gazu.asset.get_asset_type_by_name() is not case sensitive

### ISSUE THREAD

**Issue by angel-k** [cgwire/gazu#273]
The method doen't distinguish between uppercase and lowercase, which leads to incorrect results.

Example :
If I have 2 asset types :
- `ch` with id `87b3228a-0965-4d20-a613-c5ed68d6c558`
- `CH` with id `cedb4c18-c2e7-408b-ba65-b5541faabaee`

I have these 2 types because naming conventions are diffrent between some projects and we use file name for automations.

When I call `gazu.asset.get_asset_type_by_name("ch")` I get `{'id': '87b3228a-0965-4d20-a613-c5ed68d6c558', 'name': 'ch'}`
but when I call `gazu.asset.get_asset_type_by_name("CH")` I also get `{'id': '87b3228a-0965-4d20-a613-c5ed68d6c558', 'name': 'ch'}` when I should get `{'id': 'cedb4c18-c2e7-408b-ba65-b5541faabaee', 'name': 'CH'}`

We could ensure backward compatibility with the fix by adding a `case_sensitive` parameter (`false` by default) to the method.
Thank you

**Comment by frankrousseau** [comment]
Hello @angel-k,

Sorry for the late reply. After thinking about it again, we should not allow to have similar asset type names. The issue is more on the API side.
