### ISSUE TITLE
Allow managing playlists through the API

### ISSUE THREAD

**Issue by mruegenberg** [cgwire/gazu#288]
At the moment it looks like you can't manage playlists through the API, ie there's no obvious way to add a shot/task to a playlist (or remove it).

**Comment by frankrousseau** [comment]
You can manage playlists through the API (Kitsu deals only with the API), but it's true there is fo obvious way to do it.

**Comment by frankrousseau** [comment]
Some helper functions will be added to the next release.

**Comment by frankrousseau** [comment]
We added `add_entity_to_playlist` and `remove_entity_from_playlist` functions
