### ISSUE TITLE
Wrong arg sending for revision

### ISSUE THREAD

**Issue by LuciusNegareth** [cgwire/gazu#298]
Hello, 
I noticed an error with the gazu api when you want to send the revision number with `gazu.task.add_preview()`. We have an message saying  `'int' object is not iterable`.
Checking the API, i noticed that you store the revision in a dict be you don't used it.

https://github.com/cgwire/gazu/blob/7a2d3b17bce66079d27387d72fba0fa281c8802c/gazu/task.py#L868-L871

It meant to be `return raw.post(path, data, client=client)` instead

For now, setting a dict with revision a revision key in the function make it works.

```python 
gazu.task.add_preview(
            task=task,
            comment=comment,
            preview_file_path=preview,
            revision={"revision":10})
```

Thanks !

**Comment by frankrousseau** [comment]
Hello @LuciusNegareth,

Thank you for the report. Can you open a Pull Request to fix it?

**Comment by LuciusNegareth** [comment]
PR : https://github.com/cgwire/gazu/pull/299

**Comment by EvanBldy** [comment]
Thanks @LuciusNegareth for the PR :) 
I have done a new release.
