### ISSUE TITLE
online chat！！！

### ISSUE THREAD

**Issue by anuos123** [cgwire/gazu#300]
Please use https://cgwire.canny.io for any big feature request.
Desktop development, I want to send messages to anyone via person id (not via email), whether there is an api associated with the interface

**Comment by EvanBldy** [comment]
Hi @anuos123, 
I'm sorry but I don't understand what you need. Can you be more precise ? 
You want to send messages how ? A notification ?

**Comment by anuos123** [comment]
Yes, desktop notifications for personal ids

**Comment by EvanBldy** [comment]
I'm sorry but Gazu is an API it's not a desktop app, so you will have to develop that by yourself. 
Or maybe you're talking about the publisher?

**Comment by frankrousseau** [comment]
@EvanBldy browsers can emit desktop notifications.

**Comment by EvanBldy** [comment]
@frankrousseau Yes I know! 
But @anuos123 I'm sorry I don't understand what you need, can you be more precise ?

**Comment by anuos123** [comment]
Forgive my misexpression, what @frankrousseau  said is exactly what I want, I just can't find the right api interface.

**Comment by EvanBldy** [comment]
Hi @anuos123 ok I see ! 
It's a new a feature because for the moment there's no way to do that and no API (and we have to discuss if we want to add that or not to Kitsu). 
For the features requests it's on our canny : https://cgwire.canny.io/
Thanks
