### ISSUE TITLE
Publish review and set revision, permission problem

### ISSUE THREAD

**Issue by anfeo** [cgwire/gazu#325]
**Context**

Studio name: 
Gazu version: 0.9.4
Zou installation type: self-hosted

When I use this function on blender kitsu addon (modded) gazu.task.publish_preview() to pass the revision parameter I need to be logged as Studio Manager. But this is for upload preview for artist and the revision is base on the blender version file of the wip.
I don't know if it is a Gazu problem or Zou.

this is an example of the code I've added in blender kitsu addon, it work if I comment the last two parameters.
gazu.task.publish_preview(
            asdict(self),
            asdict(task_status),
            preview_file_path=preview_file_path,
            comment=comment,
            person=person,
            checklist=checklist,
            attachments=attachments,
            created_at=created_at,

            # revision = revision,
            # set_thumbnail=True,
        )

**Comment by EvanBldy** [comment]
Hi @anfeo,
Thanks for your report.
I need more information to help you can I have the log on the Zou and Gazu sides when you try to do that?
For me there's no permissions change when you are studio manager or just assigned to the task you want to add a preview.
