### ISSUE TITLE
Contribution guidelines and best practices

### ISSUE THREAD

**Issue by flablog** [cgwire/gazu#329]
As suggested by Frank on the discord, I'm opening this issue to create a discussion.

I was wandering if their exists guidelines to provide nice contributions to Gazu.

For exemple :
 * how should the functions be named
 * Where can I discusss the creation of such function ? Creating an issue ?
 * do I need one PR by function in case I'm pushing multiple fixes ?
 * where should I store the function inside the right file, by alphabetical order ? Close to the most logicial function if there is a hierarchical order of some sort ? ..?
 * Should I include the test even if I'm not sure of the routes or way to use the mockup function ?
 * are there good practices or rules for the commits description and the PR title ?

**Comment by EvanBldy** [comment]
Hello! I will try to explain point by point :) 
> * how should the functions be named

The functions are just named like : 
- new_object for creating a new object.
- update_object for updating an object.
- delete_object for deleting an object.
- get_object for getting a specific object.
- all_objects for getting all objects. 

> * Where can I discusss the creation of such function ? Creating an issue ?

Yeah, you can create an issue or a discussion. 

> * do I need one PR by function in case I'm pushing multiple fixes ?

Yeah if possible or one PR by type of functions. For example, you can do one PR if you do all the functions for departments. 

> * where should I store the function inside the right file, by alphabetical order ? Close to the most logicial function if there is a hierarchical order of some sort ? ..?

We don't have any rules like that. But maybe one day I will add a pre-commit to sort them alphabetically. 

> * Should I include the test even if I'm not sure of the routes or way to use the mockup function ?

Yeah, it's better. But if you don't know how to do that I will add them (for your current PR I can show you an example, this is very simple it's just mocking routes).

> * are there good practices or rules for the commits description and the PR title ?

For the PR title, you just have to resume concisely what you do. 
For the commits, it's almost the same but you can add some tags under brackets like [shots] if you do a function for the shots, [fix] if it's a fix, etc. You can see what we do here: https://github.com/cgwire/gazu/commits/master/

I'm closing this issue but we can continue discussing. Maybe we will try to do a guideline on our documentation.
