### ISSUE TITLE
Hi is gazu have any GUI for Maya, nuke, after effect and Houdini ready?

### ISSUE THREAD

**Issue by tws0002** [cgwire/gazu#33]
Hi,

I have a question about gazu. 
- have any GUI for Maya, nuke, after effect and Houdini ready?
- if no do u have any plan to create a cross-platform asset manager GUI tools for none programming knowledge user?

Thanks 
Desmond

**Comment by frankrousseau** [comment]
Hi @tws0002,

Thank you for asking, it's a question that will interest many people.

* Gazu have none of this. 
* We don't have anything yet. What we plan to do is to build a minimalistic UI for demo purpose. But if a studio order us some in-tools UI, we will publish it on Github.

**Comment by tws0002** [comment]
Thanks for the reply

**Comment by BigRoy** [comment]
@tws0002 are you still looking into this? I'm thinking about prototyping some tools for CG-Wire with Qt. I'm wondering what your primary needs would be? Let me know and I'll keep them in mind.

**Comment by tws0002** [comment]
Hey, @BigRoy currently I use kitsu as our studio project management system. Was thinking if there is a tool to plug into other production pipelines will be great, like Avalon. but for what I see now kitsu still don't have schedual tools to update the artist attendance. 

what I think about the tools 
- it must have an artist login system.
- a cross-platform asset manager GUI tools like Avalon.
- can automatically update work task status to kitsu when an artist working on the task.
- tools that can easily upload wip video or still to kitsu. 
- tools that can easily update or publish footage, asset, scenes and etc status to kitsu. 

this is what I have in mind now.

@BigRoy are you starting to develop tools for CG-Wire?

**Comment by frankrousseau** [comment]
We still don't have much documentation except the mentioned issue. Custom actions mainly send the current selection to an external server via a browser POST request or via an AJAX post request. The second one requires that the targeted server has CORS enabled.

**Comment by frankrousseau** [comment]
There is this repo from @BigRoy if you are still interested https://github.com/Colorbleed/qtazu

**Comment by frankrousseau** [comment]
We are working on software integration: https://github.com/cgwire/gazu-publisher

**Comment by frankrousseau** [comment]
Please open tickets directly on repositories listed above
