### ISSUE TITLE
Can't update description using the data dict in gazu.shot.update_shot_data func

### ISSUE THREAD

**Issue by flablog** [cgwire/gazu#332]
**Context**

Studio name:  lfs.coop
Gazu version: latest
Zou installation type:  docker test

**Describe the bug**

Using 
```python
data = {"description": "My Description}
gazu.shot.update_shot_data(shot, data)
```
Does not update the description
Which is weird, because apparently description is stored in the data in the `new_shot()` function: https://github.com/cgwire/gazu/blob/296aeaa07725a4fb96a4118f07588bb7399774a3/gazu/shot.py#L344

**Expected behavior**
Providing a "description" field in data, should update the description
instead of using the `update_shot()`

I've created a `update_shot_description()` function that I might push in PR. This could make it simplier than `update_shot()` and less dangerous as we can only update the description and nothing else. But that is not fixing the expected behavior.

**Comment by EvanBldy** [comment]
Hi @flablog,
The ```gazu.shot.update_shot_data``` function just updates a shot's "data" column, it is a jsonb column (key value). So it will only change values for that column. 
The description is a text column, so you need to use ```gazu.shot.update_shot``` for that. If you want to only update the description field see my example :
```python
import gazu
shot_id = "UUID"
shot_to_update = {"id": shot_id, "description": new description}
updated_shot = gazu.shot.update_shot(shot_to_update)
```

I'm closing this issue, if it's not clear to you you can reopen it.
