### ISSUE TITLE
Cannot update assets

### ISSUE THREAD

**Issue by anuos123** [cgwire/gazu#339]
Error:

gazu.exception.ParameterException: ('data/entities/948d38ed-faa6-4bd4-9cb9-35d6d1f24493', '(psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type uuid: ""\nLINE 1: ...1b7-f469-48af-aca9-7c6d944231ea\'::UUID, source_id=\'\'::UUID, ...\n  

Describe the bug:
In a test project, the code will work, but in a formal project, it will report errors.

Code:
```
if not asset_dict.get('preview_file_id'):
    asset_dict['preview_file_id'] = None

if asset_dict.get('ready_for') == 'None':
    asset_dict['ready_for'] = None

gazu.asset.update_asset(asset_dict)
```

**Comment by frankrousseau** [comment]
Meanwhile, we fix this problem. Can you set the source_id field to None (`asset["source_id"] = None`) ?

**Comment by anuos123** [comment]
> Meanwhile, we fix this problem, can you set the source_id field to None (`asset["source_id"] = None`) ?
I'm getting the asset dictionary by the "entity_id", which doesn't have the key to the "soruce_id".

**Comment by anuos123** [comment]
if not asset_dict.get('source_id'):
    asset_dict['source_id'] = None
gazu.asset.update_asset(asset_dict)

Even though I added source_id = None before the update, this error still occurs.

**Comment by anuos123** [comment]
![image](https://github.com/user-attachments/assets/8e48d18d-e51e-4b49-bee7-894bf6be934f)
This is due to episode_id: "导致的异常, which can be fixed by setting asset_dict['episode_id'] = None.
We can close this issue,Thank,framrpisseau.

**Comment by frankrousseau** [comment]
Great thank you!
