### ISSUE TITLE
gazu.task.all_task_statuses

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#47]
Hello,

While using Gazu, I realized a lack that forced me to have hard data in the code.

I would like to recover the ***TaskStatuses*** but since the documentation, I find only that concerning ***TaskTypes*** ...

If you have a solution to list all the statuses, can you tell me how to proceed?

Otherwise it would be convenient to have a dedicated function for this purpose ```gazu.task.all_task_statuses```.

**Comment by frankrousseau** [comment]
Thank you @Arubinu for reporting! 

This function is definitely missing. You can add it by contributing. It's quite easy to do (see the source code).

If you don't have time for this, we planned to work on the client documentation next week. We can add this function at this time.

**Comment by frankrousseau** [comment]
This function was added in the 0.6.9 version of Gazu.
