### ISSUE TITLE
HTTP(HTML) errors with gazu.client.upload

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#48]
Hello,

I had problems uploading videos, an error appeared, but no details on it since it is the one that interprets the JSON that causes problem.

By modifying the ```gazu.client.upload``` function, I managed to get the http 413 error (sent in HTML format via NGinx).
So, would it be possible to add an exception that would return these errors, to easily fix these problems?

I think it's not necessary to say it, but you never know. I use the ```gazu.task.add_preview``` function to send this.

**Comment by frankrousseau** [comment]
Thank you again for reporting. We'll handle that case next week. Basically, it's managed here:
https://github.com/cgwire/gazu/blob/master/gazu/client.py#L148-L176

It seems that the Nginx configuration is wrong (file size limit looks to be too low).

**Comment by frankrousseau** [comment]
In the latest vension (0.6.9) we handle 413 errors. Can you confirm that it works as expected?

**Comment by Arubinu** [comment]
It should be good, even if we fixed the problem of NGinx last time. Thank you.
