### ISSUE TITLE
Installing zou on windows

### ISSUE THREAD

**Issue by mhdmhd** [cgwire/gazu#51]
Hi

Installing zou on windows gives an error related to Uwsgi , the error is about os.uname.
I noticed the installation for Linux, is installing on windows is possible?

Thanks

**Comment by frankrousseau** [comment]
Hello @mhdmhd 

We do not support Windows installation and we don't use uwsgi anymore. We use Gunicorn instead. For Windows installation we recommend you to use a Virtual Machine and use Linux inside this VM.

**Comment by frankrousseau** [comment]
Btw, we have a Slack too where you can meet CG Professionals : https://slack.cg-wire.com

**Comment by mhdmhd** [comment]
Thanks for the fast reply.

**Comment by frankrousseau** [comment]
@mhdmhd Can we close this issue?
