### ISSUE TITLE
gazu.task.get_task_by_name() fails for role Supervisor and lower

### ISSUE THREAD

**Issue by BigRoy** [cgwire/gazu#59]
### Issue

When using `gazu.task.get_task_by_name` it works fine when logged in as the Studio Manager, but it fails when logged in as a Supervisor or CG Artist even though it's on a project they are assigned to and online they are capable of seeing exactly that resulting task. As such, online they are allowed to see it but are declined authentication through gazu.

##### Error message

```python
# gazu.exception.NotAllowedException: data/tasks?name=main&entity_id={entity_id}&task_type_id={task_type_id}
# Traceback (most recent call last):
#   File "P:\pipeline\2.1_dev\git\gazu\gazu\task.py", line 205, in get_task_by_name
#     entity_id=entity["id"]
#   File "P:\pipeline\2.1_dev\git\gazu\gazu\client.py", line 250, in fetch_first
#     entries = get(url_path_join('data', path))
#   File "P:\pipeline\2.1_dev\git\gazu\gazu\client.py", line 119, in get
#     check_status(response, path)
#   File "P:\pipeline\2.1_dev\git\gazu\gazu\client.py", line 198, in check_status
#     raise NotAllowedException(path)
# gazu.exception.NotAllowedException: data/tasks?name=main&entity_id={entity_id}&task_type_id={task_type_id}
```
_Not sure if it would've been a security issue, but I renamed the ids to `{entity_id}` and `{task_type_id}` - if you were wondering why it looked like that._

### Workaround

Is there a workaround?

In the documentation I noticed just now this function is deprecated, however I'm clueless as to how I would otherwise get the task for an asset. I noticed there is `all_tasks_for_entity_and_task_type`, but how could a single task have the same task type more than once? :) Is that what the `"main"` differentiator was for?

**Comment by BigRoy** [comment]
Actually, it does seem that instead `gazu.task.all_tasks_for_entity_and_task_type(entity, task_type)` succeeds instead. So that should be the right method to get it.

However, how multiples of the same tasks can be present on a single entity I don't know yet - would love to know more about it.

**Comment by frankrousseau** [comment]
Yes this function only makes sense when used with shotgun synchronization. But it doesn't makes sense with Kitsu.

**Comment by frankrousseau** [comment]
Can we close this issue?

**Comment by BigRoy** [comment]
Yes, because the workaround works. For closing this, here's example code on how to still get it by task name:
```python
task_type = gazu.task.get_task_type_by_name(task_name)
tasks = gazu.task.all_tasks_for_entity_and_task_type(entity, task_type)

# if you want to ensure to use the "main" task
task = next(task for task in tasks if task["name"] == "main")

# or if you don't care but want to ensure just one task of the type exists on the entity
assert len(tasks) == 1, (
    "Not exactly a single task found, instead found: %s (%s)" % (
        len(tasks), tasks
    )
)
```
