### ISSUE TITLE
gazu.task.add_preview doesn't error when upload fails

### ISSUE THREAD

**Issue by BigRoy** [cgwire/gazu#60]
### Issue

It seems that `gazu.task.add_preview` silently fails when it failed to upload and attach a preview to the comment. Additionally it does not return the result that helps to identify whether the upload succeeded. As such, it appears as if the upload succeeded but it doesn't show it online.

This seems to be due to the fact that it does return the result from the [`client.post`](https://github.com/cgwire/gazu/blob/d08a9a53efde0ecb386c922196dde327fcacdfd9/gazu/task.py#L543) but ignores any return information from [`client.upload`](https://github.com/cgwire/gazu/blob/d08a9a53efde0ecb386c922196dde327fcacdfd9/gazu/task.py#L545) which does identify that the upload fails.

The error I got from the `client.upload` (when printing that inside the function) in this case was:
```python
{u'message': u'Normalization failed.'}
```

**Comment by BigRoy** [comment]
Actually it seems that the returned data that is currently returned also fails to return the correct `extension` in the return data, etc. (It always shows `.mp4` as extension, even when uploading an image).

However, when upload succeeds the result from `client.upload` does return the correct data. This makes me think:

1. Is the `client.post()` actually necessary? Should it maybe _only_ do the `client.upload`?
2. The function should return the result from `client.upload` as opposed to the result from `client.post`?

**Comment by BigRoy** [comment]
Did some more debugging:

> 1. Is the client.post() actually necessary? Should it maybe only do the client.upload?

Currently it is, yes. Because it needs the resulting id from the `client.post` to correctly upload the file preview.

> 2. The function should return the result from client.upload as opposed to the result from client.post?

Yes, it should - because then you can actually see what the resulting upload ended up doing.

> {u'message': u'Normalization failed.'}

The resulting error is coming from `zou` here: https://github.com/cgwire/zou/blob/e4c43dd5ad2a6c1911b0de52e85e1eca09cc396b/zou/app/blueprints/previews/resources.py#L178 which I think could be due to recent changes (2 days ago) with [this commit](https://github.com/cgwire/zou/commit/bfb66b02b7f7c14b16b4f1ed53f50d2fa3700433)

Since the resulting error is only logged (I believe only in the running zou instance) I can't really debug it on the running CG-Wire instance that is hosted online by CG-Wire. Unless I'm able to look into those logs?

Anyway, my first guess was:

- _This was not the issue!_ It could be due to the integer division [here](https://github.com/cgwire/zou/commit/bfb66b02b7f7c14b16b4f1ed53f50d2fa3700433#diff-d70ec93683a320eb3add8a3f30b5a460R60) because if `PIL.Image.size` returns a tuple of pixel sizes in width/height, if they are both integers then depending on the running Python version this could result in Integer divison as opposed to returning a decimal point refactor size. This is **not** the case for Python 3+. I believe the zou instances run on Python 3+ so this is likely not the source of the issue.

But then *I found it* - it failed to normalize because my Project did not have any resolution set. Once I set that to `1920x1080` it directly succeeded. As such the issue must be [here](https://github.com/cgwire/zou/commit/bfb66b02b7f7c14b16b4f1ed53f50d2fa3700433#diff-896722177372494811fca1e4fa5146e5R258). But where it exactly fails is hard to know without the logged error. ;)

**Comment by frankrousseau** [comment]
I added a `UploadErrorException` when a file processing fails on the server side. That's not totally accurate, but it should do the job. What do you think about it?

**Comment by frankrousseau** [comment]
https://github.com/cgwire/gazu/pull/72/commits/b3f75c9826ee01a71cca93ca4aacd5038118dc99
