### ISSUE TITLE
Special characters with gazu.project.get_project_by_name()

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#71]
Hello,

I discovered a search problem when using the `gazu.project.get_project_by_name()` method.
The use of special characters does not cause errors, nor does it return the desired project!

 @frankrousseau 's solution is to use the character ASCII code of the character in hexadecial, and it works perfectly (at least with the `&` character).
Example: & => %26

**Comment by frankrousseau** [comment]
Thank you @Arubinu for the report!

**Comment by Arubinu** [comment]
I do not know if there is a better fix, but by adding the following in the `gazu.project.get_project_by_name()` method, that should fix the problem!

```
tmp = ''
for c in project_name:
	tmp += '%%%X' %  ord( c )
project_name = tmp
```

**Comment by frankrousseau** [comment]
It should be fixed with last release. Can you try again? I used the standard lib to manage it (`urllib`).
