### ISSUE TITLE
episode_id not work in new_asset method

### ISSUE THREAD

**Issue by Arubinu** [cgwire/gazu#87]
Hello,

As said in the title, `episode_id` is not taken into account (same when using `source_id` in `extra_data`).

In the meantime I made a fix by doing a `gazu.client.put()` to change the value of `source_id` after its creation!

**Comment by frankrousseau** [comment]
The `source_id` field is not an extra data. It's a field that is located directly on the instance like `asset["source_id"] = episode_id`.

**Comment by Arubinu** [comment]
Okay, but suddenly it's a problem on the Zou side, I presume?

**Comment by frankrousseau** [comment]
Yes because the `source_id` field should not appear to you. Everything should be abstracted by the API.

**Comment by frankrousseau** [comment]
I fixed the problem on both Gazu and Zou sides. Can you try again?

**Comment by Arubinu** [comment]
Tested on the latest version of Docker CGWire, works perfectly :)
