### ISSUE TITLE
delete_comment(): Not existing function

### ISSUE THREAD

**Issue by Tilix4** [cgwire/gazu#91]
Hi,
I'd like to be able to handle a project only with the API, I can add_comment but I cannot remove/delete any this way.
It'd be very useful to have a `gazu.task.delete_comment(my_comment)` / `gazu.task.remove_comment(my_comment)` function.

**Comment by frankrousseau** [comment]
Ok, thank you for reporting. It's something you can add easily to Gazu. The path to run a deletion is: 
`/api/data/tasks/${taskId}/comments/${commentId}`.

**Comment by frankrousseau** [comment]
Hello again @Tilix4,
I published a new version with this function. Can you try it?
