### ISSUE TITLE
gazu.task.get_task_by_name() doesn't work if logged as Supervisor

### ISSUE THREAD

**Issue by Tilix4** [cgwire/gazu#94]
I don't know how permissions are supposed to work, but if I'm logged as Supervisor, I cannot use `gazu.task.get_task_by_name()`.

Did I miss some documentation about it?

**Comment by frankrousseau** [comment]
Nop it's possible there is some restriction there. Are you sure that the supervisor is a member of the team project?

**Comment by Tilix4** [comment]
Yes absolutely.

**Comment by frankrousseau** [comment]
It will be fixed in next release.
