### ISSUE TITLE
gazu.shot.new_sequence() cannot be used for a short film

### ISSUE THREAD

**Issue by Tilix4** [cgwire/gazu#95]
The method is made like this`gazu.shot.new_sequence(project, episode, name)`.

If I want to create a Sequence for a shot film, `gazu.shot.all_episodes_for_project()` returns `[]`, then `gazu.shot.new_sequence` raises an error when called.

**Comment by frankrousseau** [comment]
Did you try this function by setting `episode` with `None`?

**Comment by Tilix4** [comment]
Yes, I get a `TypeError: 'NoneType' object is not subscriptable`

**Comment by frankrousseau** [comment]
It is fixed in the new version (`0.7.4`) ? Can you try again? 
The signature changed, it's now `gazu.shot.new_sequence(project, name, episode=episode)`

**Comment by Tilix4** [comment]
It works, thanks!
