### ISSUE TITLE
'data' from handler is not consistent with gazu.task.get_task()'s requirement

### ISSUE THREAD

**Issue by Tilix4** [cgwire/gazu#97]
With the handler, for a `task:update`, I get a _data_ dict with only one key:
`{'task_id': 'f094fdff-5fc9-417a-817c-86573904947d'}`

`gazu.task.get_task()` requires a dict with a `'id'` key.

I have to hack to make it work:
```
task =  {'id': data.get('task_id')}
current_task = gazu.task.get_task(task)
```

If I pass the `data` object without anything, I get a key missing error.

PS: I used a daemon handler for this test.

**Comment by frankrousseau** [comment]
From what is in the code, `gazu.task.get_task(data.get('task_id'))` should work.

**Comment by Tilix4** [comment]
Yes sure, but I don't understand why this is necessary ;)
